version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    restart: always
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "8081:8081"
    volumes:
      - ./client:/app
    restart: always
    depends_on:
      - db
      - server
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
